# PingCalculator Configuration File

# ----------------------------------------------------------------------------

# After calculated, this will be sent
# Replacement:   %player : player's name
#                %ping   : player's ping

ping-message: Â§aYour ping is %ping

# ----------------------------------------------------------------------------